name: image_exif_data
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image: ^4.5.4
  exif: ^3.3.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.0
  url_launcher: ^6.3.1
  camerawesome: 2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
